### ISSUE TITLE
貌似遇到同样的问题

### ISSUE THREAD

**Issue by wujingquan** [WindTraveler/vue-issue#1]
我貌似遇到跟你一样的问题，还没有解决。
`ERROR in ./src/shop/src/pages/index/index.vue?vue&type=template&id=e82bbd42& (./node_modules/_vue-loader@15.4.2@vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/_vue-loader@15.4.2@vue-loader/lib??vue-loader-options!./src/shop/src/pages/index/index.vue?vue&type=template&id=e82bbd42&)
Module build failed (from ./node_modules/_vue-loader@15.4.2@vue-loader/lib/loaders/templateLoader.js):
TypeError: Cannot read property 'split' of null
    at splitPath (C:\2333\sima2\node_modules\_prettier@1.13.7@prettier\third-party.js:5376:25)
    at Object.exports.sync [as findParentDir] (C:\2333\sima2\node_modules\_prettier@1.13.7@prettier\third-party.js:5403:20)
    at loadPlugins (C:\2333\sima2\node_modules\_prettier@1.13.7@prettier\index.js:26838:36)
    at C:\2333\sima2\node_modules\_prettier@1.13.7@prettier\index.js:31220:16
    at Object.format (C:\2333\sima2\node_modules\_prettier@1.13.7@prettier\index.js:31241:12)
    at actuallyCompile (C:\2333\sima2\node_modules\_@vue_component-compiler-utils@2.3.1@@vue\component-compiler-utils\dist\compileTemplate.js:97:29)
    at compileTemplate (C:\2333\sima2\node_modules\_@vue_component-compiler-utils@2.3.1@@vue\component-compiler-utils\dist\compileTemplate.js:29:16)
    at Object.module.exports (C:\2333\sima2\node_modules\_vue-loader@15.4.2@vue-loader\lib\loaders\templateLoader.js:42:20)
 @ ./src/shop/src/pages/index/index.vue?vue&type=template&id=e82bbd42& 1:0-259 1:0-259
 @ ./src/shop/src/pages/index/index.vue
 @ ./src/shop/src/pages/index/index.js`

关键报错：
`Module build failed (from ./node_modules/_vue-loader@15.4.2@vue-loader/lib/loaders/templateLoader.js):
TypeError: Cannot read property 'split' of null`

老哥你这个问题现在解决了吗？

**Comment by wujingquan** [comment]
我已经解决了。

**Comment by WindTraveler** [comment]
好的，我刚刚收到消息提醒😂
